# Generated by Django 3.0.5 on 2020-08-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], null=True),
        ),
    ]
