# Generated by Django 3.0.5 on 2020-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_auto_20200803_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')]),
        ),
    ]
