# Generated by Django 3.0.5 on 2020-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0008_auto_20200806_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
