# Generated by Django 3.0.5 on 2020-08-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_titles', '0002_auto_20200808_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=1),
        ),
    ]
